analysis-paths:
- analyses
clean-targets:
- target
- dbt_packages
macro-paths:
- macros
model-paths:
- models
models:
  sales_data:
    example:
      +materialized: view
name: sales_data
profile: sales_data
seed-paths:
- seeds
snapshot-paths:
- snapshots
test-paths:
- tests
version: 1.0.0
